config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # 消してもいいみたい？→get 'messages/index'
  root to: "rooms#index"
  resources :users, only: [:edit, :update]
  # roomsが親で、messagesが子という親子関係になるので、チャットルームに属しているメッセージという意味
  resources :rooms, only: [:new, :create, :destroy] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user
  has_one_attached :image # MessagesテーブルとActive Storageのテーブルで管理された画像ファイルのアソシエーション。
  # 「content」カラムに、presence: trueを設けることで、空の場合はDBに保存しないというバリデーションを設定している。
  # validatesのunlessオプションにメソッド名を指定することで、「メソッドの返り値がfalseならばバリデーションによる検証を行う」という条件
  validates :content, presence: true, unless: :was_attached?
  # was_attached?メソッドは、self.image.attached?という記述によって、画像があればtrue、なければfalseを返す
  def was_attached?
    self.image.attached?
  end
end

app/models/room.rb
class Room < ApplicationRecord
  # usersテーブルと中間テーブルのアソシエーション
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_many :messages, dependent: :destroy
  # 「ルーム名が存在（presence）している場合のみ作成可（true）」というバリデーション
  validates :name, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  # usersテーブルとroomsテーブルのアソシエーション
  belongs_to :room
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # roomsテーブルと中間テーブルのアソシエーション
  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
  #名前の入力が空の場合はDBに保存しない
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_actionで呼び出すことで、アクションを実行する前にログインしていなければログイン画面に遷移
  before_action :authenticate_user!
  # configure_permitted_parameters（←deviseでの追加カラム設定を行うメソッド）
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name]) # permit(:アクション, キー: [:追加したいカラム])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    # @messageには、Message.newで生成した、Messageモデルのインスタンス情報を代入
    # @roomには、paramsに含まれているroom_idを代入
    @message = Message.new
    @room = Room.find(params[:room_id]) # チャットルームに関する情報
    # チャットルームに紐付いている全てのメッセージ（@room.messages）
    @messages = @room.messages.includes(:user) # N+1問題をincludesメソッドで解消→ユーザー情報を1度のアクセスでまとめて取得
  end

  def create
    # @room.messages.newでチャットルームに紐づいたメッセージのインスタンスを生成し、message_paramsを引数にして、privateメソッドを呼び出し
    # 生成したインスタンスを@messageに代入し、saveメソッドでメッセージの内容をmessagesテーブルに保存
    @room = Room.find(params[:room_id]) # チャットルームに関する情報
    @message = @room.messages.new(message_params)
    if @message.save
      redirect_to room_messages_path(@room)
    else
      @messages = @room.messages.includes(:user)
      render :index
    end
  end

  private

  def message_params
    # パラメーターの中に、ログインしているユーザーのidと紐付いている、メッセージの内容contentを受け取れるように許可
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
  end

  def new
    # form_withに渡す引数として、値が空のRoomインスタンスを@roomに代入
    @room = Room.new
  end

  def create
    # ルーム作成時の値をDBに保存できるようにしている
    @room = Room.new(room_params)
    # 保存の成功・失敗による条件分岐
    # 成功した場合はredirect_toメソッドでルートパスにリダイレクト
    if @room.save
      redirect_to root_path
    # 失敗した場合はrenderメソッドでrooms/new.html.erbのページを表示
    else
      render :new
    end
  end

  def destroy
    room = Room.find(params[:id]) # チャットルームの情報を取得している
    room.destroy # destroyアクションは、削除するだけなのでビューの表示は不要→roomはインスタンス変数にする必要なし
    redirect_to root_path
  end

  private
  # 配列として受け取ったデータを含むストロングパラメーターの定義
  def room_params
    params.require(:room).permit(:name, user_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    # userの更新情報が保存できたときroot（チャット画面）にリダイレクト
    if current_user.update(user_params)# ストロングパラメーター
      redirect_to root_path
    # userの更新情報が保存できなかったときedit(編集画面)のビューを表示
    else
      render :edit
    end
  end

  private

  def user_params
    # 「name」と「email」の編集を許可
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_main_chat.html.erb
<div class="chat-header">
  <div class="left-header">
    <div class="header-title">
      <%= @room.name %>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <!--削除するチャットルームを区別するために、定義している@roomを引数にし、room_path(@room)と指定している-->
      <%= link_to "チャットを終了する", room_path(@room), method: :delete %>
    </div>
  </div>
</div>

<div class="messages">
  <!--render partial: 'message'で_message.html.erbを部分テンプレートとして読み込んでいる-->
  <!--collection: @messagesでeachメソッドのように@messageの要素の数だけ繰り返し部分テンプレートを表示させている-->
  <%= render partial: 'message', collection: @messages %>
</div>
<!--@roomには「指定のチャットルームのレコード情報」、@messageには「Messageモデルのからのインスタンス（Message.new）」-->
<%= form_with model: [@room, @message], class: 'form', local: true do |f| %>
  <div class="form-input">
    <%= f.text_field :content, class: 'form-message', placeholder: 'type a message' %>
    <label class="form-image">
      <span class="image-file">画像</span>
      <%= f.file_field :image, class: 'hidden' %>
    </label>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
<% end %>

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <!-- 投稿したユーザー名情報を出力する -->
      <!--messagesテーブルのuser_idに紐付いているユーザー名を、user.nameと記述することで取得-->
      <%= message.user.name %>
    </div>
    <div class="message-date">
      <!-- 投稿した時刻を出力する -->
      <!--messagesテーブルのcreated_atカラムから、投稿した時刻を取得-->
      <%= l message.created_at %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <!-- 投稿したメッセージ内容を記述する -->
      <!--messagesテーブルのcontentカラムから、メッセージの内容を取得-->
      <%= message.content %>
    </div>
    <!--画像が添付されている場合、モデルから画像ファイルを呼び出して引数に記述し、画像を表示するimg要素を生成している-->
    <!--.variant(resize: '500x500')で画像ファイルの表示サイズを指定している-->
    <%= image_tag message.image.variant(resize: '500x500'), class: 'message-image' if message.image.attached? %>
  </div>
</div>

app/views/messages/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name">
    <!--ログインユーザーの名前を表示ログインユーザー編集画面へのパスを指定-->
    <%= link_to current_user.name, edit_user_path(current_user) %>
  </div>
  <div class="create-room">
    <!--サイドバーのボタンからチャットルーム新規作成画面へ遷移-->
    <%= link_to "チャットを作成する", new_room_path %>
  </div>
</div>

<div class="rooms">
  <!--eachメソッドで全てのチャットルーム名を表示する処理を繰り返し実行-->
  <!--「|room|」の部分は変数名なので命名規則はない-->
  <% current_user.rooms.each do |room| %>
    <div class="room">
      <div class="room-name">
        <!--チャットルーム名をクリックすると、messagesコントローラーのindexアクションが実行され、チャットルームのページに遷移-->
        <!--room.nameの「name」は、roomsテーブルのカラム名-->
        <%= link_to room.name, room_messages_path(room) %>
      </div>
    </div>
  <% end %>
</div>

app/views/messages/index.html.erb
<div class="wrapper">
  <div class="side-bar" >
    <%= render "side_bar" %>
  </div>
  <div class="chat">
    <%= render "main_chat" %>
  </div>
</div>

app/views/rooms/index.html.erb
<!--チャットルーム未選択時はサイドバーのみの表示になるようにしている-->
<div class='wrapper'>
  <div class='side-bar'>
    <%= render "messages/side_bar" %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
        <!--ユーザー名一覧をプルダウン表示させる-->
        <select name="room[user_ids][]">
          <option value="">チャットするユーザーを選択してください</option>
          <!--ログインユーザーはプルダウンに表示させない-->
          <% User.where.not(id: current_user.id).each do |user| %>
            <!--選択したユーザーの情報をparamsで扱えるようにパラメーターを送る-->
            <!--paramsの中身 {"room" => {"user_ids" => ["選択したユーザーのid"]}}-->
            <option value=<%= user.id %>><%= user.name %></option>
          <% end %>
        </select>
        <!--パラメーターにログイン中ユーザーのidを含める-->
        <!--paramsの中身 {"room" => {"user_ids" => ["選択したユーザーのid", "現在ログインしているユーザーのid"]}}-->
        <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <!--ログアウト後にログイン画面へ遷移-->
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>